server:
  port: 8989

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bdqn?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    #\u914D\u7F6E\u5728\u65E5\u5FD7\u4E2D\u6253\u5370\u51FA\u6267\u884C\u7684 SQL \u8BED\u53E5\u4FE1\u606F\u3002
    show-sql: true
    #\u8FD9\u4E2A\u53C2\u6570\u662F\u5728\u5EFA\u8868\u7684\u65F6\u5019\uFF0C\u5C06\u9ED8\u8BA4\u7684\u5B58\u50A8\u5F15\u64CE\u5207\u6362\u4E3A InnoDB \u7528\u7684
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

