spring:
  redis:
    database: 0
    host: 172.16.2.54
    port: 6379
    lettuce:
      pool:
        #最大的连接数
        max-active: 8
        #最大等待时间
        max-wait: -1
        #最大的空闲链接
        max-idle: 8

