server:
  port: 5555


spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/bdqn?serverTimezone=GMT&useSSL=false

#mybatis:
#  config-location: classpath:Mybatis-Config.xml

#mybatis-plus:
#  #配置mapper.xml文件读取位置信息
#  mapper-locations: classpath*:mapper/*.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.lenovo.hawk.mapper
#  # 全局mapper映射数据库配置
#  global-config:
#    db-config:
#      #数据库大写下划线转换
#      capital-mode: true
#      #配置逻辑删除字段
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#    refresh: true
#  configuration:
#    #配置返回数据库(column下划线 -> java驼峰式)
#    map-underscore-to-camel-case: true
#    #缓存配置false,默认全部重新读取
#    cache-enabled: false
